version: '3.8'

services:
  app:
    build: .
    container_name: go-markdown-notes
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NOTES_DIR=/app/notes
      - LOG_LEVEL=info
    volumes:
      - ./notes:/app/notes
      - ./api:/app/api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: go-markdown-notes-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - app
  #   restart: unless-stopped

volumes:
  notes:
    driver: local
